apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-backend.yaml
  - path: patch-frontend.yaml

images:
  - name: stirlingtools/stirling-pdf
    newTag: 2.14.2-fat