apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirling-pdf-frontend
  namespace: stirling-pdf
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: stirling-pdf-frontend
          image: stirlingtools/stirling-pdf:latest