apiVersion: v1
kind: ConfigMap
metadata:
  name: stirling-pdf-frontend-config
  namespace: stirling-pdf
data:
  MODE: "FRONTEND"
  SECURITY_BACKENDURL: "http://stirling-pdf-backend-service.stirling-pdf.svc.cluster.local:8080"
  VITE_API_BASE_URL: "http://stirling-pdf-backend-service:8080"