apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirling-pdf-frontend
  namespace: stirling-pdf
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: stirling-pdf-frontend
  template:
    metadata:
      labels:
        app: stirling-pdf-frontend
    spec:
      containers:
      - name: stirling-pdf-frontend
        image: stirlingtools/stirling-pdf:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: stirling-pdf-frontend-config
        resources:
          requests:
            memory: "2Gi"
            cpu: "400m"
          limits:
            memory: "3Gi"
            cpu: "1500m"