apiVersion: v1
kind: Service
metadata:
  name: stirling-pdf-backend-service
  namespace: stirling-pdf
spec:
  type: ClusterIP
  selector:
    app: stirling-pdf-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080